# Application configuration

spring:
  application:
    name: poke-flop

xslt:
  base-path: /templates
  cache-templates: true

pdf:
  storage:
    location: ${PDF_STORAGE_LOCATION:pdf-storage}  # Default to 'pdf-storage' if not specified
  templates:
    location: ${PDF_TEMPLATES_LOCATION:templates}   # Default to 'templates' if not specified

# Logging configuration
logging:
  level:
    com.sigmundgranaas.floppy: DEBUG
    org.apache.fop: INFO

# Server configuration
server:
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB
  max-http-request-header-size: 10MB
